# ── PVC（申请 10Gi 华为云 EVS 云硬盘，任务4）─────────
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-disk        # 华为云 EVS StorageClass
  resources:
    requests:
      storage: 10Gi
